---
- name: X11| Ajout de la clef google
  rpm_key: 
    key: '{{ google_key_url }}'
    state: present

- name: X11| Ajout du repo terminix
  yum_repository:
    name:        terminix
    description: Terminix repository
    baseurl:     http://download.opensuse.org/repositories/home:/gnunn/CentOS_7/
    enabled:     yes
    gpgcheck:    yes
    gpgkey:      '{{ terminix_key_url }}'


- name: X11| Ajout du repo google
  yum_repository:
    name:        google
    description: Google repository
    baseurl:     http://dl.google.com/linux/rpm/stable/$basearch
    enabled:     no
    gpgcheck:    yes
    gpgkey:      '{{ google_key_url }}'


- name: X11| Ajout du repo chrome
  yum_repository:
    name:        google-chrome
    description: Google Chrome repository
    baseurl:     http://dl.google.com/linux/chrome/rpm/stable/$basearch
    enabled:     yes
    gpgcheck:    yes
    gpgkey:      '{{ google_key_url }}'

- name: X11| Ajout du repo GTalk
  yum_repository:
    name:        google-talk
    description: Google Talk repository
    baseurl:     http://dl.google.com/linux/talkplugin/rpm/stable/$basearch
    enabled:     no
    gpgcheck:    yes
    gpgkey:      '{{ google_key_url }}'

- name: X11| Ajout du repo hipchat
  yum_repository:
    name:        atlassian-hipchat
    description: Atlassian Hipchat repository
    baseurl:     http://hipchat.cloudsystem.fr/clients/linux/yum
    enabled:     no
    gpgcheck:    yes
    gpgkey:      https://www.hipchat.com/keys/hipchat-linux.key

- name: X11| Installation des soft bureautiques
  yum:
    name: '{{ item }}'
    enablerepo: epel
    update_cache: yes
    state: present
  with_items:
    - thunderbird
    - thunderbird-lightning
    - thunderbird-lightning-gdata
    - gparted
    - lm_sensors
    - hddtemp
    - google-chrome-stable
    - google-talkplugin
    - libreoffice-calc
    - libreoffice-draw
    - libreoffice-impress
    - libreoffice-writer
    - hexchat
    - pidgin
    - brasero
    - gnome-terminal
    - gedit
    - gimp
    - inkscape
    - phototonic
    - grub-customizer
    - alsa-plugins-pulseaudio
    - file-roller
    - cups
    - wireless-tools
#    - hipchat
    - p7zip
    - gnome-calculator
    - libpst
    - NetworkManager-wifi
    - NetworkManager-openvpn-gnome
    - youtube-dl
    - ffmpeg
    - NetworkManager-strongswan
    - xscreensaver-gl-extras
#    - pithos
    - terminix
    - conky-manager


- name: X11| Téléchargement de Atom
  get_url: url={{ atom_url_rpm }} dest={{atom_tmp_rpm}}

- name: X11| Installation d'Atom
  yum: name={{atom_tmp_rpm}}

- name: X11| Ajout de la clef nux-dextop
  rpm_key: 
    key: '{{ nux_dextop_key_url }}'
    state: present

- name: X11| Ajout du repo nux-dextop
  yum_repository:
    name:        nux-dextop
    description: nux-dextop repository
    baseurl:     http://li.nux.ro/download/nux/dextop/el7/$basearch
    enabled:     yes
    gpgcheck:    yes
    gpgkey:      '{{ nux_dextop_key_url }}'

- name: X11| Installation des soft media
  yum:
    name: '{{ item }}'
    enablerepo: nux-dextop
    update_cache: yes
    state: present
  with_items:
    - clementine
    - numlockx
    - parcellite
    - shutter
    - skype
    - vlc
    - yumex
    - pangox-compat
    - libusb
    - remmina
    - remmina-plugins-rdp
    - fuse-exfat
    - exfat-utils

- name: X11| Install d'un UI sympa pour GIMP
  git:
    repo: https://github.com/doctormo/GimpPs.git
    dest: '/home/{{user_jack}}/.gimp-2.8'
    force: no
  become: true
  become_user: '{{user_jack}}'
  ignore_errors: yes
