---

google_key_url: https://dl-ssl.google.com/linux/linux_signing_key.pub
pol_key_url: http://rpm.playonlinux.com/public.gpg
terminix_key_url: http://download.opensuse.org/repositories/home:/gnunn/CentOS_7//repodata/repomd.xml.key
nux_dextop_key_url: http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro

pycharm_edition: community
pycharm_version: 2016.1.4

# VBox
virtualbox_version : 5.0
virtualbox_key_url: "https://www.virtualbox.org/download/oracle_vbox.asc"

# Vagrant
vagrant_tmp: "/tmp/"
vagrant_version: 1.8.4
vagrant_arch_ext: "x86_64"
download_vagrant: True
vagrant_file: "vagrant_{{vagrant_version}}_{{vagrant_arch_ext}}.rpm"
vagrant_url: "https://releases.hashicorp.com/vagrant/{{vagrant_version}}/{{vagrant_file}}"
vagrant_tmp_file: "{{vagrant_tmp}}/{{vagrant_file}}"


# Docker
docker_key_url: "https://yum.dockerproject.org/gpg"
docker_engine_version: '*' # latest
docker_compose_version: '1.5.2'

#Atom
atom_url_rpm: "https://atom.io/download/rpm"
atom_tmp_rpm: "/tmp/atom.rpm"

